#ifndef AVOCADO_VULKAN_INTERNAL_STRUCTURE_TYPES
#define AVOCADO_VULKAN_INTERNAL_STRUCTURE_TYPES

#include <vulkan/vulkan.h>

#define DEFINE_VARIABLE(STRUCT, STRUCT_TYPE)\
template<>\
inline constexpr VkStructureType StructureType<Vk##STRUCT> = VK_STRUCTURE_TYPE_##STRUCT_TYPE 

namespace avocado::vulkan::internal {

template<typename T>
inline constexpr VkStructureType StructureType = VK_STRUCTURE_TYPE_MAX_ENUM;

DEFINE_VARIABLE(ApplicationInfo, APPLICATION_INFO);
DEFINE_VARIABLE(CommandBufferAllocateInfo, COMMAND_BUFFER_ALLOCATE_INFO);
DEFINE_VARIABLE(CommandBufferBeginInfo, COMMAND_BUFFER_BEGIN_INFO);
DEFINE_VARIABLE(CommandPoolCreateInfo, COMMAND_POOL_CREATE_INFO);
DEFINE_VARIABLE(DeviceCreateInfo, DEVICE_CREATE_INFO);
DEFINE_VARIABLE(DeviceQueueCreateInfo, DEVICE_QUEUE_CREATE_INFO);
DEFINE_VARIABLE(FenceCreateInfo, FENCE_CREATE_INFO);
DEFINE_VARIABLE(FramebufferCreateInfo, FRAMEBUFFER_CREATE_INFO);
DEFINE_VARIABLE(GraphicsPipelineCreateInfo, GRAPHICS_PIPELINE_CREATE_INFO);
DEFINE_VARIABLE(ImageViewCreateInfo, IMAGE_VIEW_CREATE_INFO);
DEFINE_VARIABLE(InstanceCreateInfo, INSTANCE_CREATE_INFO);
DEFINE_VARIABLE(PipelineColorBlendStateCreateInfo, PIPELINE_COLOR_BLEND_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineDynamicStateCreateInfo, PIPELINE_DYNAMIC_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineInputAssemblyStateCreateInfo, PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineLayoutCreateInfo, PIPELINE_LAYOUT_CREATE_INFO);
DEFINE_VARIABLE(PipelineMultisampleStateCreateInfo, PIPELINE_MULTISAMPLE_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineRasterizationStateCreateInfo, PIPELINE_RASTERIZATION_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineShaderStageCreateInfo, PIPELINE_SHADER_STAGE_CREATE_INFO);
DEFINE_VARIABLE(PipelineVertexInputStateCreateInfo, PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO);
DEFINE_VARIABLE(PipelineViewportStateCreateInfo, PIPELINE_VIEWPORT_STATE_CREATE_INFO);
DEFINE_VARIABLE(PresentInfoKHR, PRESENT_INFO_KHR);
DEFINE_VARIABLE(RenderPassBeginInfo, RENDER_PASS_BEGIN_INFO);
DEFINE_VARIABLE(RenderPassCreateInfo, RENDER_PASS_CREATE_INFO);
DEFINE_VARIABLE(SemaphoreCreateInfo, SEMAPHORE_CREATE_INFO);
DEFINE_VARIABLE(ShaderModuleCreateInfo, SHADER_MODULE_CREATE_INFO);
DEFINE_VARIABLE(SwapchainCreateInfoKHR, SWAPCHAIN_CREATE_INFO_KHR);
DEFINE_VARIABLE(SubmitInfo, SUBMIT_INFO);

}


#undef DEFINE_VARIABLE

#endif

